Source-Pocket/source-pocket

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Whit this feature user can easily contribute to the source pocket. For Mainters, pull requests will make it easier to understand.
#15
> Github issue & pr templates and Contributing guides

- .github/auto_assign.yml
Auto assignment bot added to automize the process of adding reviewers.
`.github/CODEOWNERS`
> feat: added auto-assign bot

- docs/android-studio.md
- docs/aws.md
- docs/azure.md
- docs/docker.md
- docs/git.md
- docs/visual-studio-code.md
- docs/visualstudio.md
- docusaurus.config.js
- sidebars.js
I added "development tools pocket"
#14
> feat: development tools pocket added

- docs/front-end.md
- Brainstorming about sub-titles for front-end.md
#14
> docs: seperated to titles

- docs/gnu-linux.md
- docs/macos.md
- docs/windows.md
- docusaurus.config.js
- sidebars.js
- Operating Systems Pocket added with the titles from [SDT Discord Server.](https://discord.gg/J3PTmeFj6s)
#14
> feat: Operating Systems Pocket added

- docs/android.md
- docs/flutter.md
- docs/ios.md
- docs/reactnative.md
- docs/xamarin.md
- docusaurus.config.js
- sidebars.js
I added "mobile development pocket"
#14
> feat: mobile development pocket added

- docusaurus.config.js
- Titles found on the footer divided into two columns.
> style: change done on footer

- docs/web-development/nodejs.md
added beginner level links to nodejs
> docs: added beginner level links to nodejs

- docs/web-development/reactjs.md
added beginner level link to react.js
> docs: added beginner level link to react.js

- docs/web-development/nodejs.md
add link and customize titles
have not been included_
> docs: add link and customize titles

- docs/contribution-guide.md
- docs/web-development/angularjs.md
- docs/web-development/nodejs.md
- docs/web-development/reactjs.md
- Contribution guide written for adding PR without forking.
- Deleted useless spaces in titles.
> docs: add contribution guide and edit style of code

- docs/programming-languages/go.md
> add: go source links

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Kaan Karakaya <yusufkaan142@gmail.com>
_If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested._
have not been included_
> Deleted unused tasks in pull request template

- docs/web-development/css.md
- docs/web-development/front-end.md
- docs/web-development/javascript.md
- Splitted the links found in `front-end` category to CSS and JS categories.
> feat: split the links found in front-end category to CSS and JS categories

- docs/web-development/django.md
Simple is better than complex basit bir ingilizce ile yazılmış django rehberleri içeriyor.
> Simple is better than complex linki eklendi

- docs/operating-systems/gnu-linux.md
> add: gnu/linux source links

- docs/web-development/django.md
Tutorialspoint, Realpython ve Fullstackpython linkleri eklendi
> Bi kaç tane yeni django tutorial linki

- docs/programming-languages/computer-science.md
- docs/web-development/back-end.md
- docusaurus.config.js
- sidebars.js
- `Computer Science` and `Back-End` categories added.
#14
> docs: add new categories

- docs/web-development/django.md
> docs: add Django links

- docs/web-development/html.md
> docs: add HTML links

- docs/operating-systems/gnu-linux.md
Linux sohbetleri podcasti olarak başlattığım temel linux eğitimi serimin başlangıc seviyesi olarak yüklediğim "GNU/Linux Nedir?"bölümüdür.Başlangıç seviyesi birinin bilmesi gerekenleri içerir.
> gnu/linux nedir?entry level resource added

- docs/web-development/django.md
beginner ve advenced seviye django tutorial linkleri ekledim. Ve bir linkin başlığını daha mantıklı olacak şekilde güncelledim.
> docs: added Django links and updated a link title

- docusaurus.config.js
* Change merging branch as `dev` to optimize build time on Netlify.
Closes #75
> [#75] feat: set dev branch for merging PRs

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
* Redesigned README.md layout.
* `Related Issues & Documentation` part added to PR template.
* #54
> Changes done on README and PR Template

- docs/programming-languages/python.md
added some Python tutorial links and the official Python documentation.
> docs: add Python links

- docs/development-tools/vim.md
- sidebars.js
Sistemciler için önemli olan vim editörünün kategorisi olmaması nedeniyle eklediğim kategori ve bir kaç kaynak.
> new category

- docs/web-development/flask.md
> docs: add Flask links

- docs/embedded-systems/arduino.md
> docs: add Arduino links

- docs/programming-languages/computer-science.md
Refactoring Guru is a website that teaches design patterns and includes lessons related to refactoring with illustrative examples.
> docs: add link

- docs/embedded-systems/raspberry-pi.md
> docs: add Raspberry pi links

- docs/programming-languages/java.md
> docs: add Java links

- docs/programming-languages/python.md
> docs: add a new Python link

- docs/web-development/css.md
i have added some CSS link and youtube playlists
> docs: add CSS links

- docs/web-development/html.md
Sadi Evren Sekerin HTML video serisini ekledim.
> docs: add HTML link

- docs/databases/mysql.md
> docs: add MySQL link

- docs/web-development/javascript.md
added some new JavaScript links
> docs: add JavaScript links

- docs/web-development/wordpress.md
added a new youtube tutorial about Wordpress
> docs: add Wordpress link

- docs/web-development/vuejs.md
> docs: add VueJS links

- docs/development-tools/git.md
> docs: add Git links

- docs/web-development/flask.md
> docs: added Flask links

- docs/mobile-development/android.md
> docs: add links to android

- docs/programming-languages/computer-science.md
- Computer Science başlığına link eklendi
> docs: add link to computer science

- docs/mobile-development/android.md
- Android geliştirmeye başlagıç için Google Mühendisleri tarafından hazırlanmış video-kurs
> docs: add link to android

- docs/web-development/wordpress.md
Beginner and Intermediate links are added to WordPress Pocket.
> Updated Begginer and Intermediate

- docs/programming-languages/java.md
- A youtube channel that contains java tutorials both as coding and as visual (diagram)
> docs: add link to java

- docs/artificial-intelligence/deep-learning.md
Beginner and Intermediate One-Piece Youtube Videos about Deep Learning.
> docs: Youtube videos&playlists about Deep Learning

- docs/contribution-guide.md
- docusaurus.config.js
- new links added to ‘deep learning’ and ‘javascript’ titles.
> Ready to Deploy 🛳

- docs/programming-languages/python.md
Added some guides and helpful code example sources about Python
> docs: added some guides and examples about Python

- docs/artificial-intelligence/deep-learning.md
Some text-based and video resources about Deep Learning(PDFs, HTMLs, Academic and Online Learning Programs)
> docs: text&video sources added about Deep Learning

- docs/artificial-intelligence/machine-learning.md
Some Online Courses and text-based sources about Machine Learning.
> docs: added online sources&courses about ML

- docs/programming-languages/go.md
> docs: added online sources&courses about GoLang

- docs/mobile-development/android.md
Adding a database to an Android application
> add link to android

- docs/programming-languages/go.md
Added Go Slice Tricks Cheat Sheet and Go Book.
> docs: add go source links

- docs/programming-languages/rust.md
Added some Rust language resource links.
> Added some official Rust language resource links.

- docs/web-development/django.md
added a new Django tutorial link
> docs: added Django link

- docs/programming-languages/assembly.md
Added some links to the Assembly.md Beginner section.
Consider changing some links to the Intermediate section. Actually, I couldn't decide if its beginner, or it is an intermediate.
> docs: add new links to assembly

- docs/operating-systems/other.md
Add some links for developing own os' and a wiki.
> docs: add new links to other os

- docs/web-development/jquery.md
> docs: add JQuery links

- docs/programming-languages/c.md
> Added C resource links.

- docs/programming-languages/cplusplus.md
> Added C++ resource links.

- docs/programming-languages/go.md
> docs: add go source link

- docs/programming-languages/rust.md
Added more resource links for Rust.
> Added more resource links for Rust.

- docs/operating-systems/gnu-linux.md
Added The Linux Kernel Documentation.
> Added The Linux Kernel Documentation.

- docs/web-development/wordpress.md
Advanced Level links added + new intermediate and beginner links are added.
> Links are updated w/ Content

- docs/programming-languages/python.md
oyreten -> öğreten olarak güncellendi.
> docs: a few words corrected

- docs/programming-languages/kotlin.md
- tutorial site for beginners (like tutorialspoints)
> add link to kotlin

- docs/web-development/typescript.md
> docs: add TypeScript link

- README.md
added code owners to README.md
#56
> docs: added code owners

- docs/web-development/javascript.md
- docs/web-development/reactjs.md
- docs/web-development/vuejs.md
Added cool frontend based links (en/tr)
> docs: js, vuejs and react js links

- docs/web-development/javascript.md
Bağzı eksik kelimeleri tamamladım.
> docs: fixed some words

- docs/programming-languages/assembly.md
> doc: add new links to assembly.md

- docs/programming-languages/assembly.md
doc: new links added to assembly.md
> doc: new links added to assembly.md

- docs/development-tools/git.md
Flashcard application to learn Git commands
> docs: add new link to Git

- docs/programming-languages/go.md
Reverts sdtrdev/source-pocket#155
> Revert "docs: added online sources&courses about GoLang"

- docs/programming-languages/go.md
> docs: update go.md

- docs/web-development/hosting-and-servers.md
Added HTTP Status Code list link.
> docs: add http statuses list link

- docs/operating-systems/gnu-linux.md
Added Linux Shell Tips website link.
> docs: add Linux Shell Tips website link

- docs/development-tools/git.md
Added Git Exercises website link.
> docs: add git exercises website link

- docs/programming-languages/go.md
Added Go Database SQL website link.
> docs: add Go Database SQL website

- docs/development-tools/docker.md
- New link added to Docker category and changes done on previous links.
> docs: edit docker links and add new one

- .gitignore
- docusaurus.config.js
- src/css/custom.css
- implemented DocSearch
- closes #168
> [#168] feat: implement DocSearch

- docs/operating-systems/gnu-linux.md
Added Wizard Zines website link.
> docs: add wizard zines website

- docs/programming-languages/go.md
Added Essential Go website link.
> docs: add Essential Go source

- docs/programming-languages/csharp.md
- docusaurus.config.js
- Fixed the problem with searching keyword **C#**.
- Added new links.
- Typo fixed.
close #172
> Dev to Main 🚢

- docs/programming-languages/csharp.md
> docs: add C# resources

- docs/operating-systems/gnu-linux.md
Linux ile ilgili bir link eklendi.
> docs: added linux link

- docs/programming-languages/csharp.md
- docs/programming-languages/go.md
- docs/web-development/angularjs.md
- docs/web-development/asp-net-mvc.md
- docs/web-development/jquery.md
- docs/web-development/netcore.md
- docs/web-development/nodejs.md
- docs/web-development/reactjs.md
- Resources for asp.net, jquery, .net core, nodejs, reactjs,angular,csharp and golang added.
> docs: added links to many section

- docs/web-development/asp-net-mvc.md
asp.net MVC teknolojisi için hızlandırılmış, faydalı bir kurstur. İlk contribution'umu yapmak istedim
i added a new link to the category
> asp.net MVC için crash course

- docs/graphic-design/illustrations.md
Resources for illustrations has been added.
> docs: added illustrations link.

- docs/databases/mongodb.md
- docs/development-tools/git.md
- docs/mobile-development/flutter.md
- docs/mobile-development/reactnative.md
- docs/web-development/denojs.md
- docs/web-development/django.md
- docs/web-development/laravel.md
- docs/web-development/nodejs.md
- docs/web-development/reactjs.md
- docs/web-development/vuejs.md
Resources (mostly for web development) have been added for many sections.
> Resources for Many Section has been added.

- docs/databases/postgresdb.md
- docs/development-tools/kubernetes.md
- docs/programming-languages/python.md
- docs/web-development/java-spring.md
- docs/web-development/javascript.md
- docs/web-development/reactjs.md
- sidebars.js
- Resources for `postgresdb `has been added. Also has been created `kubernetes `page in documentation section.
closes #197
> Added postgresdb resources and Created kubernetes page

- docs/artificial-intelligence/artificial-intelligence.md
- docs/artificial-intelligence/deep-learning.md
- docs/artificial-intelligence/machine-learning.md
- docs/data-science/big-data.md
- docs/data-science/statistical-learning.md
- docs/databases/postgresdb.md
- docs/development-tools/aws.md
- docs/development-tools/azure.md
- docs/development-tools/kubernetes.md
- docs/programming-languages/python.md
Many resources has been added to the relevant sections.
>  Resources for Many Section has been added

- docs/web-development/front-end.md
Added resources for frontend developers.
> docs: added frontend links.

- docs/databases/mongodb.md
- docs/development-tools/docker.md
- docs/development-tools/git.md
- docs/programming-languages/cplusplus.md
- docs/programming-languages/csharp.md
- docs/programming-languages/go.md
- docs/programming-languages/java.md
- docs/programming-languages/python.md
- docs/programming-languages/r.md
- docs/programming-languages/ruby.md
- docs/web-development/flask.md
- docs/web-development/html.md
- docs/web-development/java-spring.md
- docs/web-development/javascript.md
Resources for many section has been added. Also i fixed typo when i adding  resource to html section.
> Resources for Many Section

- docs/web-development/java-spring.md
Spring Resources has been added.
> docs: added spring links.

- docs/development-tools/kubernetes.md
Added Kubernetes from scratch link.
> add: Kubernetes resource link

- docs/game-development/unity.md
Added Unity Official Resources
> add: added new link to unity.md

- docs/graphic-design/general-design.md
- docs/graphic-design/illustrations.md
A lot of illustration and general design websites has been added to its own section
> Resources for Illustrations and General Design

- docs/game-development/unity.md
> add: unity tutorial links

- docs/game-development/unity.md
> add: unity links

- docs/programming-languages/computer-science.md
Added BilgisayarKavramlari's Data Structre playlist
Add new computer science resource
> docs: Add new computer science link

- docs/databases/mongodb.md
- docs/development-tools/docker.md
- docs/mobile-development/reactnative.md
- docs/web-development/angularjs.md
- docs/web-development/jquery.md
- docs/web-development/nodejs.md
- docs/web-development/reactjs.md
- docs/web-development/typescript.md
I found a software channel on youtube nowadays. I want everyone to benefit from this channel. Then, I added playlist links to related sections.
> Resources About Many Section

- docs/programming-languages/rust.md
Added new rust links. https://github.com/RustDili/Rust-Ogrenmek this link is turkish version of https://learning-rust.github.io/
> add: new link to category

- docs/data-science/statistical-learning.md
New Data Science Resources were added to `docs/data-science/statistical-learning.md`.
> Data Science Resources Update

- docs/programming-languages/ruby.md
- add a new link to Ruby category
> feat: added a new link for ruby

- README.md
- docs/development-tools/aws.md
- docs/development-tools/kubernetes.md
Hi team, this pull request adds new resources that helped me a lot while getting certificates in AWS and K8s fields. 
Also, I had some problems while running project on my local because of the missing Algolia API Key. So, I updated `README.md` in order to prevent anyone else having the same problem. 
Thanks!
> AWS and Kubernetes resources improved.

- docs/web-development/front-end.md
- Added link to front-end category.
> Update with StackBlitz info

- docs/mobile-development/reactnative.md
- docs/web-development/reactjs.md
Added some usefull react and react native links and articles
> Added some usefull react and react native links and articles

- docs/web-development/back-end.md
> Yeni Linkler Eklendi Back-End Nedir?

- docs/databases/mysql.md
- docs/programming-languages/dart.md
- docs/web-development/asp-net-mvc.md
- docs/web-development/css.md
- docs/web-development/php.md
> 🚣🏻‍♀️ Dev to Main 🚣🏻‍♀️

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- LICENSE
- docs/contribution-guide.md
Deleted some descriptions and fixed some broken links.
> Improvements on some files

- docs/web-development/typescript.md
Added interactive typescript blog link. (https://type-level-typescript.com/)
> docs: added typescript blog link
